// <auto-generated />
namespace Ioana.RealEstate.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nomenclatures2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nomenclatures2));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281611563_Nomenclatures2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
