//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioana.RealEstate.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ioana.RealEstate.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съгласен за снимки.
        /// </summary>
        public static string AcceptsPicsLabel {
            get {
                return ResourceManager.GetString("AcceptsPicsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави имот.
        /// </summary>
        public static string AddEstateLabel {
            get {
                return ResourceManager.GetString("AddEstateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави снимка.
        /// </summary>
        public static string AddImageLabel {
            get {
                return ResourceManager.GetString("AddImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави.
        /// </summary>
        public static string AddPhoneLabel {
            get {
                return ResourceManager.GetString("AddPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string AreaFromLabel {
            get {
                return ResourceManager.GetString("AreaFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площ.
        /// </summary>
        public static string AreaLabel {
            get {
                return ResourceManager.GetString("AreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете положителна площ.
        /// </summary>
        public static string AreaRangeErrorMessage {
            get {
                return ResourceManager.GetString("AreaRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string AreaToLabel {
            get {
                return ResourceManager.GetString("AreaToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брокер.
        /// </summary>
        public static string BrokerLabel {
            get {
                return ResourceManager.GetString("BrokerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозвънян.
        /// </summary>
        public static string CallerLabel {
            get {
                return ResourceManager.GetString("CallerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар за прозвъняването.
        /// </summary>
        public static string CallerNoteLabel {
            get {
                return ResourceManager.GetString("CallerNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string CityRegionLabel {
            get {
                return ResourceManager.GetString("CityRegionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Райони.
        /// </summary>
        public static string CityRegionsLabel {
            get {
                return ResourceManager.GetString("CityRegionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчисти.
        /// </summary>
        public static string CleanLabel {
            get {
                return ResourceManager.GetString("CleanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенти.
        /// </summary>
        public static string ClientsLabel {
            get {
                return ResourceManager.GetString("ClientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комисион.
        /// </summary>
        public static string CommisionLabel {
            get {
                return ResourceManager.GetString("CommisionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бележки.
        /// </summary>
        public static string CommisionNotesLabel {
            get {
                return ResourceManager.GetString("CommisionNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експрес Имоти.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строителство.
        /// </summary>
        public static string ConstructionStatusLabel {
            get {
                return ResourceManager.GetString("ConstructionStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип строителство.
        /// </summary>
        public static string ConstructionTypeLabel {
            get {
                return ResourceManager.GetString("ConstructionTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координати.
        /// </summary>
        public static string CoordinatesLabel {
            get {
                return ResourceManager.GetString("CoordinatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на добавяне.
        /// </summary>
        public static string DateCreatedLabel {
            get {
                return ResourceManager.GetString("DateCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи.
        /// </summary>
        public static string DocumentsLabel {
            get {
                return ResourceManager.GetString("DocumentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Асансьор.
        /// </summary>
        public static string ElevatorLabel {
            get {
                return ResourceManager.GetString("ElevatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип имот.
        /// </summary>
        public static string EstateTypeLabel {
            get {
                return ResourceManager.GetString("EstateTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип имот.
        /// </summary>
        public static string EstateTypesLabel {
            get {
                return ResourceManager.GetString("EstateTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Асоцииран потребител.
        /// </summary>
        public static string EstateUserLabel {
            get {
                return ResourceManager.GetString("EstateUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string FloorFromLabel {
            get {
                return ResourceManager.GetString("FloorFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подовa настилкa.
        /// </summary>
        public static string FlooringTypeLabel {
            get {
                return ResourceManager.GetString("FlooringTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етаж.
        /// </summary>
        public static string FloorLabel {
            get {
                return ResourceManager.GetString("FloorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете цяло число.
        /// </summary>
        public static string FloorNaNErrorMessage {
            get {
                return ResourceManager.GetString("FloorNaNErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string FloorToLabel {
            get {
                return ResourceManager.GetString("FloorToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзавеждане.
        /// </summary>
        public static string FurnishingTypeLabel {
            get {
                return ResourceManager.GetString("FurnishingTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзавеждане.
        /// </summary>
        public static string FurnishingTypesLabel {
            get {
                return ResourceManager.GetString("FurnishingTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гараж.
        /// </summary>
        public static string GarageLabel {
            get {
                return ResourceManager.GetString("GarageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отопление.
        /// </summary>
        public static string HeatingInstallationsLabel {
            get {
                return ResourceManager.GetString("HeatingInstallationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравей.
        /// </summary>
        public static string HelloLabel {
            get {
                return ResourceManager.GetString("HelloLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткосрочен наем.
        /// </summary>
        public static string IsShortTermRentLabel {
            get {
                return ResourceManager.GetString("IsShortTermRentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дограма.
        /// </summary>
        public static string JoineryTypeLabel {
            get {
                return ResourceManager.GetString("JoineryTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Географска ширина.
        /// </summary>
        public static string LatitudeLabel {
            get {
                return ResourceManager.GetString("LatitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несоциирана.
        /// </summary>
        public static string LeaveWithoutUserLabel {
            get {
                return ResourceManager.GetString("LeaveWithoutUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogInLabel {
            get {
                return ResourceManager.GetString("LogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string LogOffLabel {
            get {
                return ResourceManager.GetString("LogOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Географска дължина.
        /// </summary>
        public static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to избери.
        /// </summary>
        public static string MultiselectPlaceholder {
            get {
                return ResourceManager.GetString("MultiselectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена.
        /// </summary>
        public static string NamesLabel {
            get {
                return ResourceManager.GetString("NamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нови Имоти.
        /// </summary>
        public static string NewRealEstatesLabel {
            get {
                return ResourceManager.GetString("NewRealEstatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бяха намерени оферти.
        /// </summary>
        public static string NoRealEstatesFoundMessage {
            get {
                return ResourceManager.GetString("NoRealEstatesFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № оферта.
        /// </summary>
        public static string OfferIdLabel {
            get {
                return ResourceManager.GetString("OfferIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете положително цяло число.
        /// </summary>
        public static string OfferIdRangeErrorMessage {
            get {
                return ResourceManager.GetString("OfferIdRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oферти.
        /// </summary>
        public static string OffersLabel {
            get {
                return ResourceManager.GetString("OffersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string OfferStatusLabel {
            get {
                return ResourceManager.GetString("OfferStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на оферта.
        /// </summary>
        public static string OfferTypeLabel {
            get {
                return ResourceManager.GetString("OfferTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string OfPagesLabel {
            get {
                return ResourceManager.GetString("OfPagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Други.
        /// </summary>
        public static string OthersLabel {
            get {
                return ResourceManager.GetString("OthersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собсвеник.
        /// </summary>
        public static string OwnerLabel {
            get {
                return ResourceManager.GetString("OwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на страница.
        /// </summary>
        public static string PageSizeLabel {
            get {
                return ResourceManager.GetString("PageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паркинг.
        /// </summary>
        public static string ParkingLotLabel {
            get {
                return ResourceManager.GetString("ParkingLotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паркомясто.
        /// </summary>
        public static string ParkingSpotLabel {
            get {
                return ResourceManager.GetString("ParkingSpotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон на собственик.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефони.
        /// </summary>
        public static string PhoneNumbersLabel {
            get {
                return ResourceManager.GetString("PhoneNumbersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете телефон на собственик.
        /// </summary>
        public static string PhonesRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PhonesRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка.
        /// </summary>
        public static string PictureLabel {
            get {
                return ResourceManager.GetString("PictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string PriceFromLabel {
            get {
                return ResourceManager.GetString("PriceFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете положителна цена.
        /// </summary>
        public static string PriceRangeErrorMessage {
            get {
                return ResourceManager.GetString("PriceRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string PriceToLabel {
            get {
                return ResourceManager.GetString("PriceToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имоти.
        /// </summary>
        public static string RealEstatesLabel {
            get {
                return ResourceManager.GetString("RealEstatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстанови.
        /// </summary>
        public static string ResetLabel {
            get {
                return ResourceManager.GetString("ResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активни филтри.
        /// </summary>
        public static string SearchSummaryLabel {
            get {
                return ResourceManager.GetString("SearchSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- избери --.
        /// </summary>
        public static string SelectDropDownText {
            get {
                return ResourceManager.GetString("SelectDropDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери снимка.
        /// </summary>
        public static string SelectImageLabel {
            get {
                return ResourceManager.GetString("SelectImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покажи на картата.
        /// </summary>
        public static string ShowOnMapLabel {
            get {
                return ResourceManager.GetString("ShowOnMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улица.
        /// </summary>
        public static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етажа.
        /// </summary>
        public static string TotalFloorsLabel {
            get {
                return ResourceManager.GetString("TotalFloorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнови имота.
        /// </summary>
        public static string UpdateEstateModel {
            get {
                return ResourceManager.GetString("UpdateEstateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актуализация.
        /// </summary>
        public static string UpdatesLabel {
            get {
                return ResourceManager.GetString("UpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string ViewLabel {
            get {
                return ResourceManager.GetString("ViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огледи.
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Година на строителство.
        /// </summary>
        public static string YearOfConstructionLabel {
            get {
                return ResourceManager.GetString("YearOfConstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете число.
        /// </summary>
        public static string YearOfConstructionNaNMessage {
            get {
                return ResourceManager.GetString("YearOfConstructionNaNMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
